ttytter needs unsafe flag set for perl

diff --git a/dtweet b/dtweet
--- a/dtweet
+++ b/dtweet
@@ -25,5 +25,6 @@ function get_tweet {
 tweet=$(get_tweet)
 
 if [ -n "$tweet" ]; then
-    echo $tweet | $twitter && echo "Tweet successful" | dmenu -b -ec -et 1 || echo "Tweet FAILED" | dmenu -b -ec -et 3
+    export PERL_SIGNALS=unsafe
+    $env echo $tweet | $twitter && echo "Tweet successful" | dmenu -b -ec -et 1 || echo "Tweet FAILED" | dmenu -b -ec -et 3
 fi
